[package]
name = "rm-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
path-absolutize = "3.1.1"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
